site_name: nerdsquad blog
site_url: http://nerdsquad.xyz
markdown_extensions:
  - footnotes
  - attr_list
theme:
  name: material
  favicon: img/favicon.ico
  logo: img/nerdsquad_v2_logo_only.svg
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4 
        name: Switch to light mode
      primary: deep orange
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep orange
